services:
  php:
    container_name: enum_php
    build: .docker/php
    volumes:
      - .:/var/www
    environment:
      PHP_IDE_CONFIG: "serverName=DoctrineEnums"
    tty: true
    stdin_open: true

  pgsql:
    container_name: enum_pgsql
    image: postgres:13
    ports:
      - 12000:5432
    environment:
      POSTGRES_DB: enum_testing
      POSTGRES_USER: enum_user
      POSTGRES_PASSWORD: enum_password
